Repository c1rcle/yellow-notes-frontend, pull requests merged in 2020-04, with the labels that each got.

#43 Implement note details component
  package.json
  src/components/layout/Navigation.js
  src/components/pages/Notes/Note.js
  src/components/pages/Notes/NoteDialog.js
  src/components/pages/Notes/index.js
  src/styles/notes.css
Labels: feature, release

#41 Implement API /notes endpoint communication
  package-lock.json
  src/App.js
  src/apis/yellowNotesApi.js
  src/components/layout/Navigation.js
  src/components/pages/Notes/Note.js
  src/components/pages/Notes/NoteContainer.js
  src/components/pages/Notes/NoteDialog.js
  src/components/pages/Notes/index.js
  src/contexts/NotesContext/actions/addNoteAction.js
  src/contexts/NotesContext/actions/editNoteAction.js
  src/contexts/NotesContext/actions/getNotesAction.js
  src/contexts/NotesContext/actions/removeNoteAction.js
  src/contexts/NotesContext/dispatchAsync.js
  src/contexts/NotesContext/index.js
  src/contexts/NotesContext/reducer.js
  src/contexts/UserContext/actions/addNoteAction.js
  src/contexts/UserContext/actions/loginAction.js
  src/contexts/UserContext/actions/registerAction.js
  src/contexts/UserContext/dispatchAsync.js
  src/contexts/UserContext/index.js
  src/contexts/UserContext/reducer.js
  src/hooks/useNoteDialog.js
  src/styles/notes.css
Labels: feature, release

#54 Fix tabbing order in dialog
  src/components/pages/Notes/NoteDialog.js
Labels: bug, release

#53 Change note details dialog buttons style
  .prettierrc
  src/components/pages/Notes/NoteDialog.js
Labels: enhancement, release

#55 Fix bugs
  src/components/pages/Notes/NoteDialog.js
  src/contexts/UserContext/dispatchAsync.js
Labels: bug, release

#59 Improved note container and note display
  package-lock.json
  package.json
  public/index.html
  src/components/layout/Navigation.js
  src/components/pages/Notes/EmptyContainer.js
  src/components/pages/Notes/Note.js
  src/components/pages/Notes/NoteContainer.js
  src/index.js
  src/styles/custom.css
  src/styles/notes.css
Labels: enhancement, release

#56 Implement loading notes
  package-lock.json
  package.json
  src/components/pages/Notes/NoteContainer.js
  src/contexts/NotesContext/actions/getNotesAction.js
  src/contexts/NotesContext/index.js
  src/contexts/NotesContext/reducer.js
Labels: feature, release

#57 Implement todo list component
  src/components/layout/Navigation.js
  src/components/pages/Notes/Note.js
  src/components/pages/Notes/NoteDialog.js
  src/components/pages/Notes/Todo/TodoItem.js
  src/components/pages/Notes/Todo/index.js
Labels: feature, release

#80 Refactor NoteDialog to smaller files
  src/components/pages/Notes/NoteDialog.js
  src/components/pages/Notes/NoteDialog/NoteDialogButtons.js
  src/components/pages/Notes/NoteDialog/NoteDialogForm.js
  src/components/pages/Notes/NoteDialog/index.js
Labels: refactorization, release

#78 Dialog enhancement
  src/components/pages/Notes/NoteDialog/NoteDialogForm.js
  src/components/pages/Notes/NoteDialog/index.js
  src/styles/custom.css
Labels: feature, release

#81 Color picker feature
  package-lock.json
  package.json
  src/components/common/ColorPicker.js
  src/components/layout/Navigation.js
  src/components/pages/Notes/Note.js
  src/components/pages/Notes/NoteDialog/NoteDialogButtons.js
  src/components/pages/Notes/NoteDialog/NoteDialogCreateFooter.js
  src/components/pages/Notes/NoteDialog/NoteDialogEditFooter.js
  src/components/pages/Notes/NoteDialog/NoteDialogForm.js
  src/components/pages/Notes/NoteDialog/index.js
  src/components/pages/Notes/Todo/TodoItem.js
  src/components/pages/Notes/Todo/index.js
  src/hooks/useNoteDialog.js
  src/styles/colorpicker.css
  src/styles/notes.css
  src/utility/colorUtility.js
Labels: feature, release

#87 Fixed color picker going off the page
  package-lock.json
  package.json
  src/components/common/ColorPicker.js
  src/components/pages/Notes/NoteDialog/NoteDialogCreateFooter.js
  src/components/pages/Notes/NoteDialog/NoteDialogEditFooter.js
  src/components/pages/Notes/NoteDialog/NoteDialogFooter.js
  src/components/pages/Notes/NoteDialog/index.js
  src/styles/colorpicker.css
Labels: bug, release

#85 Errors handling feature
  package.json
  src/App.js
  src/components/common/ErrorAlert.js
  src/components/pages/Notes/NoteDialog/index.js
  src/contexts/NotesContext/actions/addNoteAction.js
  src/contexts/NotesContext/actions/editNoteAction.js
  src/contexts/NotesContext/actions/getNotesAction.js
  src/contexts/NotesContext/actions/removeNoteAction.js
  src/contexts/NotesContext/index.js
  src/contexts/NotesContext/reducer.js
  src/contexts/UserContext/actions/registerAction.js
  src/styles/AlertTemplate.js
  src/styles/custom.css
Labels: feature, release

#88 Implement link to the note feature
  package-lock.json
  src/App.js
  src/components/pages/Notes/NoteContainer.js
  src/contexts/NotesContext/actions/getNoteAction.js
  src/contexts/NotesContext/dispatchAsync.js
  src/contexts/NotesContext/index.js
  src/contexts/NotesContext/reducer.js
  src/contexts/Provider.js
  src/contexts/UserContext/actions/loginAction.js
  src/contexts/UserContext/actions/registerAction.js
  src/contexts/UserContext/reducer.js
  src/hooks/useNoteDialog.js
Labels: feature, release

#97 Style enhancement
  src/components/layout/Navigation.js
  src/components/pages/Notes/Note.js
  src/components/pages/Notes/NoteDialog/NoteDialogFooter.js
  src/styles/notes.css
Labels: bug, enhancement, release

#111 Refactor action api calls
  src/apis/yellowNotesApiHandler.js
  src/contexts/NotesContext/actions/addNoteAction.js
  src/contexts/NotesContext/actions/editNoteAction.js
  src/contexts/NotesContext/actions/getNoteAction.js
  src/contexts/NotesContext/actions/getNotesAction.js
  src/contexts/NotesContext/actions/removeNoteAction.js
  src/contexts/UserContext/actions/loginAction.js
  src/contexts/UserContext/actions/registerAction.js
Labels: refactorization, release

#112 Note url enhancement
  src/hooks/useNoteDialog.js
Labels: enhancement, release

#113 Redirection bugs
  src/components/layout/Navigation.js
  src/components/pages/NotFound.js
  src/components/pages/Notes/NoteDialog/index.js
  src/contexts/NotesContext/reducer.js
  src/hooks/useNoteDialog.js
Labels: bug, release

#110 Note blocking and auto note saving
  src/components/pages/NotFound.js
  src/components/pages/Notes/EmptyContainer.js
  src/components/pages/Notes/Note.js
  src/components/pages/Notes/NoteDialog/NoteDialogFooter.js
  src/components/pages/Notes/NoteDialog/NoteDialogForm.js
  src/components/pages/Notes/NoteDialog/index.js
  src/components/pages/Notes/Todo/TodoItem.js
  src/components/pages/Notes/Todo/index.js
  src/contexts/NotesContext/actions/editNoteAction.js
  src/contexts/NotesContext/index.js
  src/hooks/useInterval.js
  src/hooks/useNoteAction.js
  src/hooks/useNoteDialog.js
  src/styles/notes.css
Labels: enhancement, feature, release

#114 Note dialog title enhancement
  src/components/pages/Notes/NoteDialog/NoteDialogForm.js
  src/styles/notes.css
Labels: enhancement, release

#116 Implement todo tasks sorting
  src/components/common/Spinner.js
  src/components/layout/Navigation.js
  src/components/pages/Notes/Note.js
  src/components/pages/Notes/NoteContainer.js
  src/components/pages/Notes/NoteDialog/NoteDialogForm.js
  src/components/pages/Notes/NoteDialog/index.js
  src/components/pages/Notes/Todo/index.js
  src/components/pages/Notes/index.js
  src/contexts/UserContext/reducer.js
  src/hooks/useNoteAction.js
  src/styles/notes.css
Labels: enhancement, feature, release

#118 Various bug fixes
  src/components/common/HoverableControl.js
  src/components/pages/Notes/Note.js
  src/components/pages/Notes/NoteDialog/NoteDialogFooter.js
  src/components/pages/Notes/NoteDialog/NoteDialogForm.js
  src/components/pages/Notes/NoteDialog/index.js
  src/components/pages/Notes/Todo/index.js
  src/hooks/useNoteAction.js
  src/hooks/useNoteDialog.js
  src/styles/custom.css
Labels: bug, release
