Repository c1rcle/yellow-notes-frontend, pull requests merged in 2020-05, with the labels that each got.

#120 Note auto saving bug fixes
  package-lock.json
  package.json
  src/components/pages/Notes/NoteDialog/NoteDialogFooter.js
  src/components/pages/Notes/NoteDialog/index.js
  src/contexts/NotesContext/actions/editNoteAction.js
  src/hooks/useTimeout.js
Labels: bug, release

#124 Fixed loading spinner placement
  src/components/pages/Notes/NoteContainer.js
  src/components/pages/Notes/NoteLoader.js
Labels: bug, release

#115 Sorted Colours
  src/components/common/ColorPicker.js
Labels: enhancement, release

#125 Fixed formData refresh bug
  src/components/pages/Notes/NoteDialog/index.js
Labels: bug, release

#127 Fixed regression
  src/components/pages/Notes/NoteDialog/index.js
Labels: bug, release

#132 Add tooltips to overflowing divs
  src/components/common/CustomTooltip.js
  src/components/common/OverflowingTooltip.js
  src/components/common/TooltipCustom.js
  src/components/common/controls/Email.js
  src/components/common/controls/FormButton.js
  src/components/common/controls/HoverableControl.js
  src/components/common/controls/Password.js
  src/components/layout/Navigation.js
  src/components/pages/Login.js
  src/components/pages/Notes/Note.js
  src/components/pages/Notes/NoteDialog/NoteDialogForm.js
  src/components/pages/Registration/Checkbox.js
  src/components/pages/Registration/PasswordRepeat.js
  src/components/pages/Registration/index.js
  src/styles/custom.css
Labels: feature, refactorization, release

#117 Fix hardcoded api url
  .env
  .env.development
  package.json
  src/apis/yellowNotesApi.js
Labels: refactorization, release

#134 Implement note tag request filter
  src/components/common/controls/Email.js
  src/components/common/controls/Password.js
  src/components/pages/Notes/NoteDialog/index.js
  src/components/pages/Notes/Todo/index.js
  src/components/pages/Registration/PasswordRepeat.js
  src/contexts/CategoriesContext/actions/addCategoryAction.js
  src/contexts/CategoriesContext/actions/getCategoriesAction.js
  src/contexts/CategoriesContext/actions/removeCategoryAction.js
  src/contexts/CategoriesContext/dispatchAsync.js
  src/contexts/CategoriesContext/index.js
  src/contexts/CategoriesContext/reducer.js
  src/contexts/NotesContext/actions/getNotesAction.js
  src/contexts/Provider.js
Labels: enhancement, feature, release

#133 Image inside note
  src/components/pages/Notes/Note.js
  src/components/pages/Notes/NoteDialog/NoteDialogFooter.js
  src/components/pages/Notes/NoteDialog/NoteDialogForm.js
  src/components/pages/Notes/NoteDialog/NoteImage.js
  src/components/pages/Notes/NoteDialog/NoteImageInput.js
  src/components/pages/Notes/NoteDialog/index.js
  src/styles/custom.css
  src/styles/notes.css
  src/utility/checkUrl.js
  src/utility/testImage.js
Labels: feature, release

#140 Implement emoji picker
  package-lock.json
  package.json
  src/components/common/EmojiPicker.js
  src/components/pages/Notes/NoteDialog/NoteDialogFooter.js
  src/components/pages/Notes/NoteDialog/NoteDialogForm.js
  src/components/pages/Notes/NoteDialog/index.js
  src/components/pages/Notes/Todo/index.js
  src/hooks/useActiveElement.js
Labels: feature, release

#141 ESC key bug fix
  src/components/pages/Notes/NoteDialog/index.js
Labels: bug, release

#142 Added connection error page
  package-lock.json
  package.json
  src/components/pages/ConnectionError.js
  src/components/pages/Notes/NoteContainer.js
  src/components/pages/Notes/NoteDialog/NoteDialogFooter.js
  src/components/pages/Notes/NoteDialog/NoteDialogForm.js
  src/components/pages/Notes/NoteDialog/NoteImageInput.js
  src/contexts/NotesContext/reducer.js
  src/styles/custom.css
Labels: feature, release

#143 Fix task sorting
  src/components/pages/Notes/Todo/index.js
Labels: enhancement, release

#136 Implement tag management bar
  package.json
  src/components/pages/Notes/CategoryBar/AddCategoryButton.js
  src/components/pages/Notes/CategoryBar/CategoriesContainer.js
  src/components/pages/Notes/CategoryBar/CategoryFilter.js
  src/components/pages/Notes/CategoryBar/Dialogs/CategoryDropdown.js
  src/components/pages/Notes/CategoryBar/Dialogs/CategoryNameInput.js
  src/components/pages/Notes/CategoryBar/RemoveCategoryButton.js
  src/components/pages/Notes/CategoryBar/index.js
  src/components/pages/Notes/Note.js
  src/components/pages/Notes/NoteContainer.js
  src/components/pages/Notes/NoteDialog/NoteCategoryButton.js
  src/components/pages/Notes/NoteDialog/NoteDialogFooter.js
  src/components/pages/Notes/index.js
  src/contexts/FiltersContext/index.js
  src/contexts/FiltersContext/reducer.js
  src/contexts/Provider.js
  src/styles/custom.css
Labels: feature, release
