Repository c1rcle/yellow-notes-frontend, pull requests merged in 2020-03, with the labels that each got.

#10 Registration component implementation
  .gitignore
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/components/registration/Checkbox.js
  src/components/registration/Email.js
  src/components/registration/FormButton.js
  src/components/registration/Password.js
  src/components/registration/PasswordRepeat.js
  src/components/registration/index.js
  src/contexts/Registration/index.js
Labels: feature, prototype

#12 Tooltips enhancement
  package-lock.json
  package.json
  src/App.js
  src/components/common/TooltipCustom.js
  src/components/registration/Checkbox.js
  src/components/registration/Email.js
  src/components/registration/FormButton.js
  src/components/registration/Password.js
  src/components/registration/PasswordRepeat.js
  src/components/registration/index.js
  src/contexts/Registration/index.js
Labels: enhancement, prototype

#8 Login component feature
  src/App.js
  src/components/Login.js
  src/components/common/Email.js
  src/components/common/FormButton.js
  src/components/common/Password.js
  src/components/registration/index.js
Labels: feature, prototype

#13 Project structure update and code style fixes
  src/App.js
  src/components/Login.js
  src/components/common/Email.js
  src/components/common/FormButton.js
  src/components/common/Password.js
  src/components/common/TooltipCustom.js
  src/components/pages/Login.js
  src/components/pages/Registration/Checkbox.js
  src/components/pages/Registration/PasswordRepeat.js
  src/components/pages/Registration/index.js
Labels: prototype, refactorization

#14 Notes container feature
  src/App.js
  src/components/pages/notes/Note.js
  src/components/pages/notes/NoteContainer.js
  src/components/pages/notes/index.js
  src/components/pages/notes/notes.css
Labels: feature, prototype

#15 Component transitions
  src/App.js
  src/components/common/FadingRoute.js
  src/components/pages/Notes/Note.js
  src/components/pages/Notes/NoteContainer.js
  src/components/pages/Notes/index.js
  src/components/pages/Notes/notes.css
  src/components/pages/notes/Note.js
  src/components/pages/notes/notes.css
Labels: enhancement, prototype

#18 Added .editorconfig file
  .editorconfig
  .prettierrc
Labels: enhancement, prototype

#9 Context feature
  package-lock.json
  package.json
  src/App.js
  src/components/layout/Navigation.js
  src/components/pages/Login.js
  src/components/pages/Notes/Note.js
  src/components/pages/Notes/NoteContainer.js
  src/components/pages/Notes/index.js
  src/components/pages/Registration/index.js
  src/contexts/UserContext/dispatchAsync.js
  src/contexts/UserContext/index.js
  src/contexts/UserContext/reducer.js
  src/styles/notes.css
Labels: feature, prototype

#23 Apply client's suggestions
  public/favicon.ico
  public/index.html
  src/components/common/Email.js
  src/components/common/Password.js
  src/components/layout/Navigation.js
  src/components/pages/Registration/PasswordRepeat.js
  src/components/pages/Registration/index.js
Labels: enhancement, prototype

#21 Add yellowNotesApi axios instance
  package-lock.json
  package.json
  src/apis/yellowNotesApi.js
  src/components/layout/Navigation.js
  src/contexts/UserContext/actions/addNoteAction.js
  src/contexts/UserContext/actions/checkTokenAction.js
  src/contexts/UserContext/actions/loginAction.js
  src/contexts/UserContext/actions/registerAction.js
  src/contexts/UserContext/dispatchAsync.js
  src/contexts/UserContext/reducer.js
Labels: feature, prototype

#26 Implement spinners for long lasting actions
  src/apis/yellowNotesApi.js
  src/components/common/FormButton.js
  src/components/common/Spinner.js
  src/components/pages/Login.js
  src/components/pages/Registration/index.js
  src/contexts/UserContext/dispatchAsync.js
  src/contexts/UserContext/reducer.js
Labels: feature, prototype

#39 Bug fix
  src/components/common/Email.js
  src/components/common/Password.js
  src/components/layout/Navigation.js
  src/components/pages/Login.js
  src/components/pages/Registration/Checkbox.js
  src/components/pages/Registration/index.js
  src/contexts/UserContext/actions/checkTokenAction.js
  src/contexts/UserContext/actions/loginAction.js
  src/contexts/UserContext/actions/registerAction.js
  src/contexts/UserContext/dispatchAsync.js
  src/contexts/UserContext/reducer.js
Labels: bug

#42 Implemented 404 page design
  src/App.js
  src/components/common/ErrorAlert.js
  src/components/layout/Navigation.js
  src/components/pages/NotFound.js
  src/styles/navbar.css
Labels: feature, release

#45 Enhance styling and fix nav buttons layout
  src/components/layout/Navigation.js
  src/components/pages/Notes/index.js
  src/styles/navbar.css
Labels: enhancement
